[build]
builder = "nixpacks"
buildCommand = "cd server && npm ci"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/products"
timeout = 300
interval = 30
